### ISSUE TITLE
Menu appearing from right hand side of screen

### ISSUE THREAD

**Issue by 99centsappdevelopment** [balram3429/BTSimpleSideMenu#1]
Hi,

First of all, thanks for an awesome control - I've been waiting for something like this for ages!

It seems to all work well, but I do want the menu to slide out from the right hand side of the screen, not the left. How would I be able to do this?

Thanks in advance for your assistance :)

**Comment by balram3429** [comment]
Hi 99cents,

Thanks for asking.

What behavior you want in the menu except the present one.
1. Menu should slide in from left & should slide out towards right ?
2. Menu should slide in/out from right ?
3. Menu should slide in from any direction and should slide out to the opposite direction. 

Will be happy to update it.!!!

Apart from this, there is another custom control named "btSimplePopUp" for grid menu which is yet to be published on cocoacontrols. 
It is a different flavor altogether. You may be interested in that as well. It is one of my finest creation. Have a look.

**Comment by balram3429** [comment]
Will provide all options in near future.

**Comment by 99centsappdevelopment** [comment]
So how do I go about making the menu appear on the right (and slide towards the left)? And when will it be available? I'll be sure to also checkout your other control.
